How to build a https://github.com/WASdev/ci.docker.websphere-traditional[WebSphere Application Server traditional Docker] container with a https://www.ibm.com/support/knowledgecenter/SSAW57_9.0.0/com.ibm.websphere.nd.multiplatform.doc/ae/trun_app_set_dragdrop.html[monitored application deployment] directory (i.e. a "dropins" dir).

*Note:* Instructions shown using Git Bash for Windows (should be easily mapped to Linux/MacOS).

.Steps
. Clone the Docker build directory
* `git clone git@github.com:scottkurz/monitored-twas-docker.git`
. Do a docker build via:
* `cd samples/my-rest-app;  docker build -t xyz:NN .`  
* _Optional_: OR, start with my image: *scottkurz/my-rest-app:1* on DockerHub
. Run a new container with:
[source,bash]
----
REPO_ROOT="$(cygpath -w $(pwd))"  # From Git Bash / Cygwin

winpty docker run --name my-rest-app \
-v "$REPO_ROOT\volumes\PASSWORD.txt":/tmp/PASSWORD \
-v "$REPO_ROOT\volumes\monitored-app-dir":/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/monitoredDeployableApps \
-p 9043:9043 -p 9443:9443 -p 7777:7777 \
-e ENABLE_BASIC_LOGGING=true \
-it  scottkurz/my-rest-app:1
----
[start=4]
. Start with any application project, e.g.:
* `git clone https://github.com/scottkurz/MyRestApp`
. Make changes or whatever, and build it, (not shown, e.g. using RAD/WDT Eclipse tooling with an _Export WAR_):
. Copy into the mounted directory at location *.../monitored-app-dir/servers/server1*, e.g.:
   `cp MyRestApp.war "$REPO_ROOT\volumes\monitored-app-dir\servers\server1"`
. Watch the app get installed:
....
[6/13/19 2:38:46:982 UTC] 00000049 AppManagement I   CWLDD0021I: Event id 580239227-1. Application MyRADRest_war is started on:
WebSphere:cell=DefaultCell01,node=DefaultNode01,server=server1,status=success.
....
